export const RESTAURANTS = [
  {
    id: 1,
    name: "Burger Palace",
    rating: 4.8,
    reviews: 1234,
    address: "Bradshaw St, Overland Park, KS 66213",
    hours: "Open • Closes 2 AM",
    cuisine: "American",
    priceRange: "$$",
    lat: 40.7128,
    lon: -74.0060,
    image: "https://placehold.co/400x200",
    thumbnail: "https://placehold.co/100x100",
    distance: "0.8 mi",
    deliveryTime: "15-25 min",
    deliveryFee: "$2.99",
    popular: ["Classic Burger", "Cheese Fries", "Milkshake"],
    isNew: false,
    isFavorite: true,
    promoCode: "BURGER20",
  },
  {
    id: 2,
    name: "Pizza Heaven",
    rating: 4.5,
    reviews: 876,
    address: "Bradshaw St, Overland Park, KS 66213",
    hours: "Open • Closes 12 AM",
    cuisine: "Italian",
    priceRange: "$$",
    lat: 40.7200,
    lon: -73.9980,
    image: "https://placehold.co/400x200",
    thumbnail: "https://placehold.co/100x100",
    distance: "1.2 mi",
    deliveryTime: "20-30 min",
    deliveryFee: "$1.99",
    popular: ["Pepperoni Pizza", "Garlic Knots", "Tiramisu"],
    isNew: true,
    isFavorite: false,
    promoCode: "",
  },
  {
    id: 3,
    name: "Sushi Express",
    rating: 4.7,
    reviews: 543,
    address: "Bradshaw St, Overland Park, KS 66213",
    hours: "Open • Closes 10 PM",
    cuisine: "Japanese",
    priceRange: "$$$",
    lat: 40.7050,
    lon: -74.0100,
    image: "https://placehold.co/400x200",
    thumbnail: "https://placehold.co/100x100",
    distance: "2.5 mi",
    deliveryTime: "25-40 min",
    deliveryFee: "$3.99",
    popular: ["California Roll", "Miso Soup", "Tempura"],
    isNew: false,
    isFavorite: true,
    promoCode: "SUSHI15",
  },
  {
    id: 4,
    name: "Taco Fiesta",
    rating: 4.3,
    reviews: 321,
    address: "Bradshaw St, Overland Park, KS 66213",
    hours: "Open • Closes 11 PM",
    cuisine: "Mexican",
    priceRange: "$",
    lat: 40.7150,
    lon: -73.9900,
    image: "https://placehold.co/400x200",
    thumbnail: "https://placehold.co/100x100",
    distance: "0.5 mi",
    deliveryTime: "10-20 min",
    deliveryFee: "$0.99",
    popular: ["Street Tacos", "Guacamole", "Churros"],
    isNew: true,
    isFavorite: false,
    promoCode: "",
  },
];